server:
  port: 8083

spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        handleAppointmentEvent-in-0:
          destination: appointment-events
        handleAppointmentReminder-in-0:
          destination: appointment-reminders
        handleAdminSecurityEvent-in-0:
          destination: admin-security-events
      function:
        definition: handleAppointmentEvent;handleAppointmentReminder;handleAdminSecurityEvent

medclinic:
  telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN:}
    admin-chat-id: ${TELEGRAM_ADMIN_CHAT_ID:}

logging:
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
